networks:
  traefik_web:
    external: true
  traefik_internal:

volumes:
  traefik_web_certificates:

services:
  traefik:
    image: traefik:3.6.6
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik_web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_web_certificates:/certificates
      - ./traefik/hashed_pass:/hashed_pass
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.traefik_web-http.rule=Host(`traefik.stresstable.xyz`)
      - traefik.http.routers.traefik_web-http.entrypoints=http
      - traefik.http.routers.traefik_web-http.middlewares=https-redirect
      - traefik.http.middlewares.traefik-auth.basicauth.usersfile=/hashed_pass/traefik_pass
      - traefik.http.routers.traefik_web-https.rule=Host(`traefik.stresstable.xyz`)
      - traefik.http.routers.traefik_web-https.entrypoints=https
      - traefik.http.routers.traefik_web-https.tls=true
      - traefik.http.routers.traefik_web-https.tls.certresolver=le
      - traefik.http.routers.traefik_web-https.middlewares=traefik-auth
      - traefik.http.routers.traefik_web-https.service=api@internal
      - traefik.http.services.traefik_web.loadbalancer.server.port=8080
    command:
      - --providers.docker
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email=info@stressatble.xyz
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=http
      - --accesslog=true
      - --accesslog.format=json
      - --accesslog.fields.defaultmode=keep
      - --accesslog.fields.headers.defaultmode=keep
      - --log=true
      - --log.level=DEBUG
      - --api.dashboard=true

  fea_app:
    image: nginx:alpine
    container_name: fea-app
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_web
      - traefik.constraint-label=traefik_web
      - traefik.http.routers.fea_app-http.rule=Host(`fea-app.stresstable.xyz`)
      - traefik.http.routers.fea_app-http.entrypoints=http
      - traefik.http.routers.fea_app-http.middlewares=https-redirect
      - traefik.http.routers.fea_app-https.rule=Host(`fea-app.stresstable.xyz`)
      - traefik.http.routers.fea_app-https.entrypoints=https
      - traefik.http.routers.fea_app-https.tls=true
      - traefik.http.routers.fea_app-https.tls.certresolver=le
      - traefik.http.services.fea_app.loadbalancer.server.port=80
    networks:
      - traefik_web
